/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({ 'app' : IDL.Null, 'game' : IDL.Null });
export const ApkMetadata = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'downloadUrl' : IDL.Text,
  'fileSize' : IDL.Nat,
  'version' : IDL.Text,
  'modFeatures' : IDL.Vec(IDL.Text),
  'category' : Category,
  'iconUrl' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addListing' : IDL.Func([ApkMetadata], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteListing' : IDL.Func([IDL.Text], [], []),
  'getAllListings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ApkMetadata))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListing' : IDL.Func([IDL.Text], [IDL.Opt(ApkMetadata)], ['query']),
  'getListingsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(IDL.Tuple(IDL.Text, ApkMetadata))],
      ['query'],
    ),
  'getListingsByCategoryText' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, ApkMetadata))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchListings' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, ApkMetadata))],
      ['query'],
    ),
  'updateListing' : IDL.Func([IDL.Text, ApkMetadata], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({ 'app' : IDL.Null, 'game' : IDL.Null });
  const ApkMetadata = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'downloadUrl' : IDL.Text,
    'fileSize' : IDL.Nat,
    'version' : IDL.Text,
    'modFeatures' : IDL.Vec(IDL.Text),
    'category' : Category,
    'iconUrl' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addListing' : IDL.Func([ApkMetadata], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteListing' : IDL.Func([IDL.Text], [], []),
    'getAllListings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ApkMetadata))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListing' : IDL.Func([IDL.Text], [IDL.Opt(ApkMetadata)], ['query']),
    'getListingsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(IDL.Tuple(IDL.Text, ApkMetadata))],
        ['query'],
      ),
    'getListingsByCategoryText' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, ApkMetadata))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchListings' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, ApkMetadata))],
        ['query'],
      ),
    'updateListing' : IDL.Func([IDL.Text, ApkMetadata], [], []),
  });
};

export const init = ({ IDL }) => { return []; };